version: "3.8"
services:
  #dev:
  #  build:
  #    context: ./dev/
  #    dockerfile: ./dev/Dockerfile
  #  container_name: mlops-dev
  #  command: /bin/sh
  #  # ports: # add ports for loading data if needed
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
      args:
        GIT_BRANCH: ${GIT_BRANCH:-unspecified}
        GIT_HEAD: ${GIT_HEAD:-unspecified}
    environment:
      LOG_PREDICTIONS: "true"
    container_name: mlops-api
    restart: always
    volumes:
      - ./api/:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --reload-include *.pickle --host 0.0.0.0
  prometheus:
    image: prom/prometheus
    container_name: mlops-prometheus-local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus/:/prometheus # store time series here
    ports: 
      - 9090:9090