version: "3.8"
services:
  mlops:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_BRANCH: ${GIT_BRANCH:-unspecified}
        GIT_HEAD: ${GIT_HEAD:-unspecified}
    container_name: mlops
    environment:
      LOG_PREDICTIONS: "true"
      MODE: ${MODE:-dev}
      MODEL_STORE: "mlflow"
    #restart: always
    ports:
      - 8000:8000 # api
      - 8888:8888 # jupyterlab
    volumes:
      - ./:/app
      # By default, use tmpfs memory for files that may store personal data.
      # These files only persist for as long as the container runs. 
      # WARNING: Only edit if you know what you are doing!
      - type: tmpfs
        target: /app/local_data
      # NOTE: dev/data will be included in the /app volume!
  prometheus-local:
    image: prom/prometheus
    container_name: mlops-prometheus-local
    volumes:
      # By default, only store prometheus time series temporarily as they may contain sensitive data
      # WARNING: Only edit if you know what you are doing!
      - type: tmpfs 
        target: /prometheus
      # to store prometheus logs locally and persistently, use the following instead:
      # - ./prometheus/prometheus/:/prometheus
      # share volume on prometheus config file:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090