version: "3.8"
services:
  ml-api:
    build: .
    container_name: ml-api
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: ['uvicorn',
              'main:app',
              '--reload',
              '--reload-include',
              '*.pickle',
              "--host",
              "0.0.0.0"]  
    
