global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'mlops-api-metrics'
    basic_auth:
        # WARNING: this is not secure way to handle secrets!
        username: 'stanleyjobson'
        password: 'swordfish'

    static_configs:
      - targets: ['mlops:8000']
